### ISSUE TITLE
Showing stacktraces in the console

### ISSUE THREAD

**Issue by tw-balsandhu** [dalzymendoza/twu-biblioteca-dalzy#2]
An error message appears when I choose an option which does not any options on the starting screen.

`Welcome to Biblioteca. Your one-stop-shop for great book titles in Bangalore!
[M] Main Menu
[Q] Quit Application
1
java.lang.NoSuchMethodException
[Ljava.lang.StackTraceElement;@65b3120a`

While testing our applications it's crucial for us to see where an error may be thrown and what it pertains to, but to a regular user this will appear merely as a system malfunction.

**Comment by dalzymendoza** [comment]
These error outputs are from the usage of reflection for determining what method to call given a user input. From the refactoring of the BibliotecaApp class, I have decided to remove the usage of reflection and instead use a simpler switch statement, so these error outputs have also been removed.

However, if I find the need to use System.err again, I will use a Logger class instead. Thanks!
