### ISSUE TITLE
Overloaded BibliotecaApp Class; RE: Refactoring

### ISSUE THREAD

**Issue by tw-balsandhu** [dalzymendoza/twu-biblioteca-dalzy#3]
With our BibliotecaApp class we want to keep it as minimal as possible. As you've mentioned the BibliotecaApp class is handling a lot of responsibility - it's great that you noticed that :)

When a class starts to contain logic which does not relate to its specifications it is best to create a new, more distinct representation of that object.

In OO it is good practice to name our classes after nouns which will play a role in your application. Separating our classes in this way also eases pain when a new set of eyes attempt read and understand the code.

Have a go at extracting out some of the logic into one or more new classes.

**Comment by dalzymendoza** [comment]
The main issue I found was the changing input options available to the user depending on "where they are" in the system and the logic that had to be ran according to those options. So what I have decided to do is:
- create a Service abstract class and every set of related options and logic will be a Service subclass (e.g. HomeService, ReturnBookService)
- create a ServiceHandler class that will keep track of the current Service the user is on and handle the user input which will then be passed to the current Service for processing
- and manage the movement between services by allowing Service classes to change the current Service attribute of the ServiceHandler

I think you can liken it to Activities or Fragments in an Android application? Do you think this was an alright direction?
