### ISSUE TITLE
Editing Stories

### ISSUE THREAD

**Issue by tw-balsandhu** [dalzymendoza/twu-biblioteca-dalzy#4]
When wanting to edit a story it is always necessary to provide justification regarding your decision.

That being said, having new input is always a great thing so never hesitate to question the content of a story. 

In the case of this project feel free to play around with the wording, if you have issues with any of the other specifications please let me know.

**Comment by dalzymendoza** [comment]
Alrighty! That makes sense. :)

Should I close this and open a more specific issue if/when I do have question/s for other specs? Or just leave this open and add more comments for future spec questions?

**Comment by tw-balsandhu** [comment]
Lets close this one and open a new one when you see fit, that way it's easier to resolve each individual issue :)
