### ISSUE TITLE
Expressive test names

### ISSUE THREAD

**Issue by tw-balsandhu** [dalzymendoza/twu-biblioteca-dalzy#5]
A pattern that I often like to follow when naming tests is to structure them like so:

**should**DoThis**When/If**GivenThis

This approach allows us to be more mindful when expressing exactly what we want our outcome to be.

Here is an example test name from your app:
returnCheckedOutBookUsingIncorrectId

While this provides some context it is unclear exactly what the outcome should be without looking into the code.

An example of a more expressive name could be:
shouldShowErroWhenCheckingOutWithIncorrectId

This might give the reader a little more insight into exactly what we're testing for. Of course this is only one approach to creating more expressive test names, feel free to use this or look into another way of structuring the name.

**Comment by dalzymendoza** [comment]
Thanks for the pattern! I have updated the test names in commits 5576c4094bc9e709a99a62ba67ec2c73e0de98d3 and 3dcb3bdb8d7b8cc245fee8465ee7d154b06581c0
